package com.neteasemall.pojo;

import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated
     */


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.subtitle
     *
     * @mbggenerated
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.main_image
     *
     * @mbggenerated
     */
    private String mainImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.stock
     *
     * @mbggenerated
     */
    private Integer stock = Integer.MAX_VALUE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.status
     *
     * @mbggenerated
     */
    private Integer sold = 1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.status
     *
     * @mbggenerated
     */

    private BigDecimal soldPrice;

    private Integer soldQuantity=0;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.status
     *
     * @mbggenerated
     */
    private Integer status = 1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neteasemall_product.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    private Integer cartLabel=0;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neteasemall_product
     *
     * @mbggenerated
     */
    public Product(@Param("id") Integer id,  @Param("name") String name, @Param("subtitle") String subtitle, @Param("mainImage") String mainImage,  @Param("detail") String detail, @Param("price") BigDecimal price, @Param("stock") Integer stock, @Param("sold") Integer sold, @Param("soldPrice") BigDecimal soldPrice, @Param("soldQuantity") Integer soldQuantity, @Param("status") Integer status, @Param("cartLabel") Integer cartLabel,Date createTime, Date updateTime) {
        this.id = id;
        this.name = name;
        this.subtitle = subtitle;
        this.mainImage = mainImage;
        this.detail = detail;
        this.price = price;
        this.stock = stock;
        this.sold = sold;
        this.soldPrice = soldPrice;
        this.soldQuantity=soldQuantity;
        this.status = status;
        this.cartLabel=cartLabel;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neteasemall_product
     *
     * @mbggenerated
     */
    public Product() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neteasemall_product.id
     *
     * @return the value of neteasemall_product.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neteasemall_product.id
     *
     * @param id the value for neteasemall_product.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neteasemall_product.name
     *
     * @return the value of neteasemall_product.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neteasemall_product.name
     *
     * @param name the value for neteasemall_product.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neteasemall_product.subtitle
     *
     * @return the value of neteasemall_product.subtitle
     * @mbggenerated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neteasemall_product.subtitle
     *
     * @param subtitle the value for neteasemall_product.subtitle
     * @mbggenerated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neteasemall_product.main_image
     *
     * @return the value of neteasemall_product.main_image
     * @mbggenerated
     */
    public String getMainImage() {
        return mainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neteasemall_product.main_image
     *
     * @param mainImage the value for neteasemall_product.main_image
     * @mbggenerated
     */
    public void setMainImage(String mainImage) {
        this.mainImage = mainImage == null ? null : mainImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neteasemall_product.detail
     *
     * @return the value of neteasemall_product.detail
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neteasemall_product.detail
     *
     * @param detail the value for neteasemall_product.detail
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neteasemall_product.price
     *
     * @return the value of neteasemall_product.price
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neteasemall_product.price
     *
     * @param price the value for neteasemall_product.price
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neteasemall_product.stock
     *
     * @return the value of neteasemall_product.stock
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neteasemall_product.stock
     *
     * @param stock the value for neteasemall_product.stock
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neteasemall_product.status
     *
     * @return the value of neteasemall_product.status
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neteasemall_product.status
     *
     * @param status the value for neteasemall_product.status
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neteasemall_product.create_time
     *
     * @return the value of neteasemall_product.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neteasemall_product.create_time
     *
     * @param createTime the value for neteasemall_product.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neteasemall_product.update_time
     *
     * @return the value of neteasemall_product.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neteasemall_product.update_time
     *
     * @param updateTime the value for neteasemall_product.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }


    public Integer getSold() {
        return sold;
    }

    public void setSold(Integer sold) {
        this.sold = sold;
    }

    public BigDecimal getSoldPrice() {
        return soldPrice;
    }

    public void setSoldPrice(BigDecimal soldPrice) {
        this.soldPrice = soldPrice;
    }

    public Integer getSoldQuantity() {
        return soldQuantity;
    }

    public void setSoldQuantity(Integer soldQuantity) {
        this.soldQuantity = soldQuantity;
    }

    public Integer getCartLabel() {
        return cartLabel;
    }

    public void setCartLabel(Integer cartLabel) {
        this.cartLabel = cartLabel;
    }
}